CREATE DATABASE sisgea;
USE sisgea;

--CURRENCIES
CREATE TABLE currencies (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    iso CHAR(4) NOT NULL
);

--WALLETS
CREATE TABLE wallets (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    balance DECIMAL(20,2) NOT NULL DEFAULT 0.00,
    currency INT NOT NULL
);

--MOVEMENT_KINDS
CREATE TABLE movement_kinds (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    detail TINYTEXT
);

--MOVEMENTS
CREATE TABLE movements (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    detail TINYTEXT,
    amount DECIMAL(20,2) NOT NULL,
    type BIT NOT NULL,
    datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    currency INT NOT NULL,
    --user INT NOT NULL,
    wallet INT NOT NULL,
    kind INT NOT NULL
);